ShepherdsLittleHelper/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShepherdsLittleHelper.Models
{
    public class Group
    {
        [Key]
        public int GroupID { get; set; }
        [Display(Name ="Group")]
        public string GroupName { get; set; }

        public virtual ICollection<User> Users { get; set; }

    }
}

ShepherdsLittleHelper/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShepherdsLittleHelper.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ShepherdsLittleHelper.Controllers
{
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Groups
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                return View(currentUser.Groups.ToList());
            }
            return Redirect("/Home/Index");
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Group group = db.Groups.Find(id);
                if (group == null)
                {
                    return HttpNotFound();
                }
                //Bring group's users to detail view
                ViewBag.users = group.Users;
                return View(group);
            }
            return RedirectToAction("/Index");
        }
        [HttpPost]
        //suspect this is causing errors, comment it out for now
        //[ValidateAntiForgeryToken]
        public ActionResult Details(int? id, string email)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Group group = db.Groups.Find(id);
                if (group == null)
                {
                    return HttpNotFound();
                }
                List<User> toAddList = db.Users.Where(u => u.Email.ToLower() == email.ToLower()).ToList();
                if (toAddList.Count > 0)
                {
                    User toAdd = toAddList[0];
                    toAdd.Groups.Add(group);
                    db.SaveChanges();
                    ViewBag.email = toAdd.Email;
                }
                //Make users visible on a POST to not throw errors
                ViewBag.users = group.Users;
                return View(group);
            }
            return RedirectToAction("/Index");
        }

        // GET: Groups/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("/Index");
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupID,GroupName")] Group group)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                    User currentUser = UserManager.FindById(User.Identity.GetUserId());
                    db.Groups.Add(group);
                    currentUser.Groups.Add(group);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(group);
            }
            return RedirectToAction("/Index");
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Group group = db.Groups.Find(id);
                if (group == null)
                {
                    return HttpNotFound();
                }
                return View(group);
            }
            return RedirectToAction("/Index");
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupID,GroupName")] Group group)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(group).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(group);
            }
            return RedirectToAction("/Index");
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Group group = db.Groups.Find(id);
                if (group == null)
                {
                    return HttpNotFound();
                }
                return View(group);
            }
            return RedirectToAction("/Index");
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Request.IsAuthenticated)
            {
                Group group = db.Groups.Find(id);
                db.Groups.Remove(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("/Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShepherdsLittleHelper/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShepherdsLittleHelper.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ShepherdsLittleHelper.Controllers
{
    public class LocationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Locations
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var locations = UserLocations(currentUser);
                return View(locations.ToList());
            }
            return Redirect("/Home/Index");
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Location location = db.Locations.Find(id);
                if (location == null)
                {
                    return HttpNotFound();
                }
                IEnumerable<Pet> pets = db.Pets.Where(p => p.LocationID == location.LocationID).AsEnumerable();
                ViewBag.pets = pets;
                ViewBag.currentOccupancy = pets.Count();
                ViewBag.location = location;
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName");
                return View();
            }
            return RedirectToAction("/Index");
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationID,LocationName,MaxOccupancy,LocationNotes,GroupID")] Location location)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Locations.Add(location);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName", location.GroupID);
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Location location = db.Locations.Find(id);
                if (location == null)
                {
                    return HttpNotFound();
                }
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName", location.GroupID);
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationID,LocationName,MaxOccupancy,LocationNotes,GroupID")] Location location)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(location).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName", location.GroupID);
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Location location = db.Locations.Find(id);
                if (location == null)
                {
                    return HttpNotFound();
                }
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Request.IsAuthenticated)
            {
                Location location = db.Locations.Find(id);
                db.Locations.Remove(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("/Index");
        }

        public IEnumerable<Location> UserLocations(User currentUser)
        {
            var groupIds = currentUser.Groups.Select(g => g.GroupID);
            IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.Group.GroupID)).AsEnumerable();
            return locations;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShepherdsLittleHelper/Views/Groups/Create.cshtml
@model ShepherdsLittleHelper.Models.Group

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShepherdsLittleHelper/Views/Groups/Delete.cshtml
@model ShepherdsLittleHelper.Models.Group

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShepherdsLittleHelper/Views/Groups/Details.cshtml
@model ShepherdsLittleHelper.Models.Group

@{
    ViewBag.Title = "Details";
}

<h2>Current users in @Html.DisplayFor(model => model.GroupName)</h2>


<div class="container" id="groupCon">
    @foreach (var user in ViewBag.users)
    {

        <p id="userName">@user.UserName</p>
                @*@Html.ActionLink("Edit", "Edit", new { id = model.GroupID }) |
                    @Html.ActionLink("Details", "Details", new { id = model.GroupID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = model.GroupID })*@
    }
    @using (Html.BeginForm())
    {
        <p>
            Enter an email to add to group.
        </p>
        <input type="text" name="email" />
        <input type="submit" onclick="userAdded(@ViewBag.email)" />
    }
    <br />
    <div id="userAddedMessage"></div>
    

            @*@Html.DisplayNameFor(model => model.GroupName)

            @Html.DisplayFor(model => model.GroupName)*@

    @* Here we list the users in the group by email *@

    

    
</div>
    <br />
    @Html.ActionLink("Edit", "Edit", new { id = Model.GroupID }) |
    @Html.ActionLink("Back to List", "Index")

ShepherdsLittleHelper/Views/Groups/Edit.cshtml
@model ShepherdsLittleHelper.Models.Group

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GroupID)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShepherdsLittleHelper/Views/Groups/Index.cshtml
@model IEnumerable<ShepherdsLittleHelper.Models.Group>

@{
    ViewBag.Title = "Group Index";
}

<h2>Your groups</h2>

<p>
    @Html.ActionLink("Create a group", "Create")
</p>

<div class="container">
    <div class="row">
        @foreach (var model in Model)
        {
            <div class="col-xs-12 col-sm-6 col-md-4" id="groupIndex">
                <p>@Html.DisplayFor(modelmodel => model.GroupName)</p>
                @Html.ActionLink("Add room", "Index", "Locations")
                <br />@Html.ActionLink("Add user", "Details", new { id = model.GroupID })
                <br />
                @Html.ActionLink("Edit", "Edit", new { id = model.GroupID }) ||
                @Html.ActionLink("Delete", "Delete", new { id = model.GroupID })
            </div>
        }
    </div>    
</div>