ShepherdsLittleHelper/Controllers/LocationTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShepherdsLittleHelper.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ShepherdsLittleHelper.Controllers
{
    public class LocationTasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: LocationTasks
        public ActionResult Index()
        {

            if (Request.IsAuthenticated)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var locationTaskEnum = UserTasks(currentUser);
                return View(locationTaskEnum.ToList());
            }
            return Redirect("/Home/Index");
        }

        // GET: LocationTasks/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                LocationTask locationTask = db.LocationTasks.Find(id);
                if (locationTask == null)
                {
                    return HttpNotFound();
                }
                return View(locationTask);
            }
            return RedirectToAction("/Index");
        }

        // GET: LocationTasks/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email");
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName");
                return View();
            }
            return RedirectToAction("/Index");
        }

        // POST: LocationTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "L_TaskID,TaskDescription,Frequency,Deadline,IsDone,LocationID,TaskTypeID,ApplicationUserID")] LocationTask locationTask)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.LocationTasks.Add(locationTask);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", locationTask.ApplicationUserID);
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName", locationTask.TaskTypeID);
                return View(locationTask);
            }
            return RedirectToAction("/Index");
        }

        // GET: Items/Edit
        public ActionResult ToggleDone(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationTask item = db.LocationTasks.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            if (item.IsDone)
            {
                item.ApplicationUser = null;
                item.IsDone = false;
            }
            else if (!item.IsDone)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                item.ApplicationUser = currentUser;
                item.IsDone = true;
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: LocationTasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                LocationTask locationTask = db.LocationTasks.Find(id);
                if (locationTask == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", locationTask.ApplicationUserID);
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName", locationTask.TaskTypeID);
                ViewBag.Deadline = locationTask.Deadline.Date;
                return View(locationTask);
            }
            return RedirectToAction("/Index");
        }

        // POST: LocationTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "L_TaskID,TaskDescription,Frequency,Deadline,IsDone,LocationID,TaskTypeID,ApplicationUserID")] LocationTask locationTask)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(locationTask).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", locationTask.ApplicationUserID);
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName"); ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", locationTask.LocationID);
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName", locationTask.TaskTypeID);
                return View(locationTask);
            }
            return RedirectToAction("/Index");
        }

        // GET: LocationTasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                LocationTask locationTask = db.LocationTasks.Find(id);
                if (locationTask == null)
                {
                    return HttpNotFound();
                }
                return View(locationTask);
            }
            return RedirectToAction("/Index");
        }

        // POST: LocationTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Request.IsAuthenticated)
            {
                LocationTask locationTask = db.LocationTasks.Find(id);
                db.LocationTasks.Remove(locationTask);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("/Index");
        }

        public IEnumerable<LocationTask> UserTasks(User currentUser)
        {
            var groupIds = currentUser.Groups.Select(g => g.GroupID);
            var locations = db.Locations.Where(l => groupIds.Contains(l.Group.GroupID));
            var locationIDs = locations.Select(l => l.LocationID);
            var locationTasks = db.LocationTasks.Where(t => locationIDs.Contains(t.LocationID));
            IEnumerable<LocationTask> userTasks = locationTasks.AsEnumerable();
            return userTasks;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShepherdsLittleHelper/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShepherdsLittleHelper.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ShepherdsLittleHelper.Controllers
{
    public class LocationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Locations
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var locations = UserLocations(currentUser);
                return View(locations.ToList());
            }
            return Redirect("/Home/Index");
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Location location = db.Locations.Find(id);
                if (location == null)
                {
                    return HttpNotFound();
                }
                IEnumerable<Pet> pets = db.Pets.Where(p => p.LocationID == location.LocationID).AsEnumerable();
                ViewBag.pets = pets;
                ViewBag.currentOccupancy = pets.Count();
                ViewBag.location = location;
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName");
                return View();
            }
            return RedirectToAction("/Index");
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationID,LocationName,MaxOccupancy,LocationNotes,GroupID")] Location location)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Locations.Add(location);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName", location.GroupID);
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Location location = db.Locations.Find(id);
                if (location == null)
                {
                    return HttpNotFound();
                }
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName", location.GroupID);
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationID,LocationName,MaxOccupancy,LocationNotes,GroupID")] Location location)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(location).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Group> groups = db.Groups.Where(g => groupIds.Contains(g.GroupID)).AsEnumerable();
                ViewBag.GroupID = new SelectList(groups, "GroupID", "GroupName", location.GroupID);
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Location location = db.Locations.Find(id);
                if (location == null)
                {
                    return HttpNotFound();
                }
                return View(location);
            }
            return RedirectToAction("/Index");
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Request.IsAuthenticated)
            {
                Location location = db.Locations.Find(id);
                db.Locations.Remove(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("/Index");
        }

        public IEnumerable<Location> UserLocations(User currentUser)
        {
            var groupIds = currentUser.Groups.Select(g => g.GroupID);
            IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.Group.GroupID)).AsEnumerable();
            return locations;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShepherdsLittleHelper/Views/Locations/Create.cshtml
@model ShepherdsLittleHelper.Models.Location

@{
    ViewBag.Title = "Create";
}

<h2>Create your location</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LocationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxOccupancy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxOccupancy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxOccupancy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, "Group", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShepherdsLittleHelper/Views/Locations/Delete.cshtml
@model ShepherdsLittleHelper.Models.Location

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Group.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.GroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxOccupancy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxOccupancy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationNotes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShepherdsLittleHelper/Views/Locations/Details.cshtml
@model ShepherdsLittleHelper.Models.Location

@{
    ViewBag.Title = "Details";
}

<h2>Details for @Html.DisplayFor(model => model.LocationName)</h2>

<div class="container" id="locationDet">


    <p><span id="locationDetText">@Html.DisplayNameFor(model => model.Group.GroupName)</span>: @Html.DisplayFor(model => model.Group.GroupName)</p>

    @*<dt>
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationName)
        </dd>*@
    <p><span id="locationDetText">@Html.DisplayNameFor(model => model.MaxOccupancy)</span>: @Html.DisplayFor(model => model.MaxOccupancy)</p>

    <p><span id="locationDetText">Current Occupancy</span>: @ViewBag.currentOccupancy</p>


    <p><span id="locationDetText">@Html.DisplayNameFor(model => model.LocationNotes)</span>: @Html.DisplayFor(model => model.LocationNotes)</p>

    <h3>Pets in @Html.DisplayFor(model => model.LocationName)</h3>
    @foreach (var pet in ViewBag.pets)
    {
        <p><a href="/Pets/Details/@pet.PetID">@pet.PetName</a></p>
    }
    <br />
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LocationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShepherdsLittleHelper/Views/Locations/Edit.cshtml
@model ShepherdsLittleHelper.Models.Location

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LocationID)

        <div class="form-group">
            @Html.LabelFor(model => model.LocationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxOccupancy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxOccupancy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxOccupancy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, "GroupID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShepherdsLittleHelper/Views/Locations/Index.cshtml
@model IEnumerable<ShepherdsLittleHelper.Models.Location>

@{
    ViewBag.Title = "Index";
}

<h2>Your location</h2>

<p>
    @Html.ActionLink("Add a location", "Create")
</p>
@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Group.GroupName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxOccupancy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocationNotes)
        </th>
        <th></th>
    </tr>*@

@foreach (var item in Model)
{
    <div class="container" id="locationIndex">
        <div class="col-xs-12 col-sm-6 col-md-4" >
            <p><span id="locationText">@Html.DisplayNameFor(model => model.Group.GroupName)</span>: @Html.DisplayFor(modelitem => item.Group.GroupName)</p>

            <p><span id="locationText">@Html.DisplayNameFor(model => model.MaxOccupancy)</span>: @Html.DisplayFor(modelitem => item.MaxOccupancy)</p>

            <p><span id="locationText">@Html.DisplayNameFor(model => model.LocationName)</span>: @Html.DisplayFor(modelitem => item.LocationName)</p>

            <p><span id="locationText">@Html.DisplayNameFor(model => model.LocationNotes)</span>: @Html.DisplayFor(modelitem => item.LocationNotes)</p>
            <br/>
            @Html.ActionLink("Pets", "Index", "Pets") ||
            @Html.ActionLink("Location tasks", "Index", "LocationTasks") ||
            @Html.ActionLink("Edit", "Edit", new { id = item.LocationID }) ||
            @Html.ActionLink("Details", "Details", new { id = item.LocationID }) ||
            @Html.ActionLink("Delete", "Delete", new { id = item.LocationID })
            </div>
        </div>

}