ShepherdsLittleHelper/Models/Pet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShepherdsLittleHelper.Models
{
    public class Pet
    {
        [Key]
        public int PetID { get; set; }
        [Display(Name = "Name")]
        public string PetName { get; set; }
        [StringLength(1)]
        public string Gender { get; set; }
        //Trim time off date
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Birthday { get; set; }
        [Display(Name = "Weight")]
        [DefaultValue(0)]
        public double Weight { get; set; }
        [Display(Name = "Special notes")]
        [DefaultValue("")]
        public string PetNotes { get; set; }
        [Display(Name = "Image URL")]
        [DefaultValue("")]
        public string ImageURL { get; set; }

        [ForeignKey("Location")]
        public int LocationID { get; set; }
        public virtual Location Location { get; set; }

        [ForeignKey("PetType")]
        public int PetTypeID { get; set; }
        public virtual PetType PetType { get; set; }

        //Calcualte age from DOB
        public int AgeYears
        {
            get { return (DateTime.Now - this.Birthday).Days/ 365; }
            set { }
        }

        public int AgeMonths
        {
            get { return ((DateTime.Now - this.Birthday).Days % 365) / 30; }
            set { }
        }

        public string Age
        {
            get { return this.AgeYears.ToString() + " years " + this.AgeMonths.ToString() + " months"; }
            set { }
        }
    }
}

ShepherdsLittleHelper/Models/PetType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShepherdsLittleHelper.Models
{
    public class PetType
    {
        [Key]
        public int PetTypeID { get; set; }
        [Display(Name = "Species")]
        public string PetTypeDescription { get; set; }

    }
}

ShepherdsLittleHelper/Controllers/PetTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShepherdsLittleHelper.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ShepherdsLittleHelper.Controllers
{
    public class PetTasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PetTasks
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var petTasks = UserTasks(currentUser);
                return View(petTasks.ToList());
            }

            return Redirect("/Home/Index");
        }
        
        // GET: PetTasks/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PetTask petTask = db.PetTasks.Find(id);
                if (petTask == null)
                {
                    return HttpNotFound();
                }
                return View(petTask);
            }
            return RedirectToAction("/Index");
        }

        // GET: PetTasks/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email");
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
                IEnumerable<Pet> pets = db.Pets.Where(p => groupIds.Contains(p.Location.GroupID)).AsEnumerable();
                ViewBag.PetID = new SelectList(pets, "PetID", "PetName");
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName");
                return View();
            }
            return RedirectToAction("/Index");
        }

        // POST: PetTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaskID,TaskDescription,Frequency,Deadline,PetID,TaskTypeID,ApplicationUserID")] PetTask petTask)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.PetTasks.Add(petTask);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", petTask.ApplicationUserID);
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
                IEnumerable<Pet> pets = db.Pets.Where(p => groupIds.Contains(p.Location.GroupID)).AsEnumerable();
                ViewBag.PetID = new SelectList(pets, "PetID", "PetName");
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName", petTask.TaskTypeID);
                return View(petTask);
            }
            return RedirectToAction("/Index");
        }

        // GET: PetTasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PetTask petTask = db.PetTasks.Find(id);
                if (petTask == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", petTask.ApplicationUserID);
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
                IEnumerable<Pet> pets = db.Pets.Where(p => groupIds.Contains(p.Location.GroupID)).AsEnumerable();
                ViewBag.PetID = new SelectList(pets, "PetID", "PetName");
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName", petTask.TaskTypeID);
                ViewBag.Deadline = petTask.Deadline.Date;
                return View(petTask);
            }
            return RedirectToAction("/Index");
        }
        public ActionResult ToggleDone(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PetTask item = db.PetTasks.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            if (item.IsDone)
            {
                item.IsDone = false;
                item.ApplicationUser = null;
            }
            else if (!item.IsDone)
            {
                item.IsDone = true;
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                item.ApplicationUser = currentUser;
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        // POST: PetTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaskID,TaskDescription,Frequency,Deadline,PetID,TaskTypeID,ApplicationUserID")] PetTask petTask)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(petTask).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "Email", petTask.ApplicationUserID);
                UserManager<User> UserManager = new UserManager<User>(new UserStore<User>(db));
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                var groupIds = currentUser.Groups.Select(g => g.GroupID);
                IEnumerable<Location> locations = db.Locations.Where(l => groupIds.Contains(l.GroupID)).AsEnumerable();
                ViewBag.LocationID = new SelectList(locations, "LocationID", "LocationName");
                IEnumerable<Pet> pets = db.Pets.Where(p => groupIds.Contains(p.Location.GroupID)).AsEnumerable();
                ViewBag.PetID = new SelectList(pets, "PetID", "PetName");
                ViewBag.TaskTypeID = new SelectList(db.TaskTypes, "TaskID", "TaskTypeName", petTask.TaskTypeID);
                return View(petTask);
            }
            return RedirectToAction("/Index");
        }

        // GET: PetTasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PetTask petTask = db.PetTasks.Find(id);
                if (petTask == null)
                {
                    return HttpNotFound();
                }
                return View(petTask);
            }
            return RedirectToAction("/Index");
        }

        // POST: PetTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Request.IsAuthenticated)
            {
                PetTask petTask = db.PetTasks.Find(id);
                db.PetTasks.Remove(petTask);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("/Index");
        }

        public IEnumerable<PetTask> UserTasks(User currentUser)
        {
            var groupIds = currentUser.Groups.Select(g => g.GroupID);
            var pets = db.Pets.Where(p => groupIds.Contains(p.Location.Group.GroupID));
            var petIDs = pets.Select(p => p.PetID);
            var petTasks = db.PetTasks.Where(t => petIDs.Contains(t.PetID));
            IEnumerable<PetTask> userTasks = petTasks.AsEnumerable();
            return userTasks;
        }

        protected override void Dispose(bool disposing)
        {

ShepherdsLittleHelper/Views/Pets/Create.cshtml
@model ShepherdsLittleHelper.Models.Pet

@{
    ViewBag.Title = "Pet Info";
}

<h2>Please enter the information.</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="Gender">
                    <option value="M">Male</option>
                    <option value="F">Female</option>
                    <option value="n">Neutered</option>
                    <option value="s">Spayed</option>
                </select>
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>*@
            <div class="form-group">
                @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*Calendar dropdown*@
                    <input type="date" name="Birthday" />
                    @*@Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Weight, "Must be in pounds (lbs)", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PetNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PetNotes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PetNotes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LocationID, "Room", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PetTypeID, "Speices", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("PetTypeID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PetTypeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShepherdsLittleHelper/Views/Pets/Delete.cshtml
@model ShepherdsLittleHelper.Models.Pet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete @Html.DisplayFor(model => model.PetName)?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetType.PetTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetType.PetTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
            @if (Model.Weight <= 1)
            {
                <span>lb</span>
            }
            else
            {
                <span>lbs</span>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @if (Model.Gender == "n")
            {
                <span>Neutered</span>
            }
            @if (Model.Gender == "s")
            {
                <span>Spayed</span>
            }
            @if (Model.Gender == "M")
            {
                <span>Male</span>
            }
            @if (Model.Gender == "F")
            {
                <span>Female</span>
            }
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.PetNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.ImageURL)" onerror="this.src='../../Images/file.jpg'" id="petPicture" />

        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShepherdsLittleHelper/Views/Pets/Details.cshtml
@model ShepherdsLittleHelper.Models.Pet

@{
    ViewBag.Title = "Details";
}

<h2>Details for @Html.DisplayFor(model => model.PetName)</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetType.PetTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetType.PetTypeDescription)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.PetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetName)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
            @if (Model.Weight <= 1)
            {
                <span>lb</span>
            }
            else
            {
                <span>lbs</span>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @if(Model.Gender=="n")
                {
                    <span>Neutered</span>
                }
                @if (Model.Gender == "s")
                {
                    <span>Spayed</span>
                }
                @if (Model.Gender == "M")
                {
                    <span>Male</span>
                }
                @if (Model.Gender == "F")
                {
                    <span>Female</span>
                }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PetNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.ImageURL)" onerror="this.src='../../Images/file.jpg'" id="petPicture" />

        </dd>

    </dl>
    <h3>Task for @Html.DisplayFor(model => model.PetName)</h3>
    @foreach (var petTask in ViewBag.petTasks)
    {
        <dl class="dl-horizontal">
            <dd>
                <a href="/PetTasks/Details/@petTask.TaskID">@petTask.TaskDescription</a>
            </dd>
        </dl>
    }
    <h3>Task for @Html.DisplayFor(model => model.Location.LocationName)</h3>
    @foreach (var locationTask in ViewBag.locationTasks)
    {
        <dl class="dl-horizontal">
            <dd>
                <a href="/PetTasks/Details/@locationTask.L_TaskID">@locationTask.TaskDescription</a>
            </dd>
        </dl>
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PetID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShepherdsLittleHelper/Views/Pets/Index.cshtml
@model IEnumerable<ShepherdsLittleHelper.Models.Pet>

@{
    ViewBag.Title = "Index";
}


@*
    -remove species from index page
    -fix javascript so that input is still stored (user friendlyness)





*@
<h2>Here are your pets!</h2>

<p>
    @Html.ActionLink("Add pet", "Create")
</p>
@*<tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetType.PetTypeDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetNotes)
        </th>
        <th></th>
    </tr>*@

<div class="container" id="petContainer">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-xs-12 col-sm-6 col-md-4" id="petBoarder">
                @*@Html.DisplayFor(modelItem => item.ImageURL)*@
                @*Use default image if picture not available*@
                <img src="@Url.Content(item.ImageURL)" onerror="this.src='../../Images/file.jpg'" id="petPicture" />
                <br />
                <span id="petName">@Html.DisplayFor(modelItem => item.PetName)</span>
                <br />
                <hr>
                <span id="petDisplay">@Html.DisplayNameFor(model => model.Location.LocationName)</span> : @Html.DisplayFor(modelItem => item.Location.LocationName)
                <br />
                <span id="petDisplay">@Html.DisplayNameFor(model => model.PetType.PetTypeDescription)</span> : @Html.DisplayFor(modelItem => item.PetType.PetTypeDescription)
               <br />
                <span id="petDisplay">@Html.DisplayNameFor(model => model.Gender)</span> : @*@Html.DisplayFor(modelItem => item.Gender)*@
                @if (item.Gender == "n")
                {
                    <span>Neutered</span>
                }
                @if (item.Gender == "s")
                {
                    <span>Spayed</span>
                }
                @if (item.Gender == "M")
                {
                    <span>Male</span>
                }
                @if (item.Gender == "F")
                {
                    <span>Female</span>
                }

                <br />
                <span id="petDisplay">@Html.DisplayFor(modelItem => item.Age)</span> || @Html.DisplayFor(modelItem => item.Birthday)
                <br />
                <span id="petDisplay">@Html.DisplayNameFor(model => model.Weight)</span> : @Html.DisplayFor(modelItem => item.Weight)
                @if (item.Weight <= 1)
                {
                    <span>lb</span>
                }
                else
                {
                    <span>lbs</span>
                }
                <br />
                <span id="petDisplay">@Html.DisplayNameFor(model => model.PetNotes)</span> : @Html.DisplayFor(modelItem => item.PetNotes)
                <br />
                @Html.ActionLink("Pet task", "Index", "PetTasks") ||
                @Html.ActionLink("Edit", "Edit", new { id = item.PetID }) ||
                @Html.ActionLink("Details", "Details", new { id = item.PetID }) ||
                @Html.ActionLink("Delete", "Delete", new { id = item.PetID })
            </div>
        }
    </div>
</div>